all: tests.com map2text.exe

pl2c86.exe: pl2c86.pl2 pl2c.pl2 pl2const.pl2 pl2sub.pl2 pl2var.pl2 pl2gen86.pl2
        pl2c86 pl2c86.pl2
        del tests.com

tests.com: tests.pl2 pl2c86.exe
        pl2c86 tests.pl2
        tests.com

map2text.exe: pl2c86.exe map2text.pl2
        pl2c86 map2text.pl2

clean:
        del *.com
        del *.map
